# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestUntitled():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_untitled(self):
        self.driver.get("http://127.0.0.1:8000/add_incident/")
        self.driver.set_window_size(934, 984)
        self.driver.find_element(By.ID, "id_title").click()
        self.driver.find_element(By.ID, "id_title").send_keys("Hello Everyone")
        self.driver.find_element(By.ID, "id_description").click()
        self.driver.find_element(By.ID, "id_description").send_keys("abcdabcd")
        self.driver.find_element(By.ID, "id_location").click()
        self.driver.find_element(By.ID, "id_location").send_keys("Farmgate, Dhaka")
        self.driver.find_element(By.ID, "id_service_type").click()
        self.driver.find_element(By.NAME, "Submit").click()

