# Generated by Django 5.0.2 on 2024-11-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0007_alter_incident_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
