# Generated by Django 5.0.2 on 2024-11-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0010_alter_incident_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('no Action', 'no Action'), ('on Action', 'on Action'), ('completed', 'completed')], default='no action', max_length=20),
        ),
    ]
