# Generated by Django 5.0.2 on 2024-11-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0011_alter_incident_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('No Action', 'No Action'), ('On Action', 'On Action'), ('Completed', 'Completed')], default='No Action', max_length=20),
        ),
    ]
